version: '3.9'
services:
  db:
    container_name: db
    image: postgres:14.1
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: development
    ports:
      - "5432:5432"
#    volumes:
#      - /database:/var/lib/postgresql/data
  oss:
    container_name: oss
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server --console-address ":9001" /data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: app:${DATETIME}
    environment:
      POSTGRES_HOST: 3.26.60.225
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: development
      MINIO_URL: http://3.26.60.225:9000
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
      DOMAIN_NAME: https://www.thinkmoreapp.com
      SSL_ENABLE: 'true'
      ENABLE_SWAGGER: 'true'
    restart: unless-stopped
    network_mode: "host"
    depends_on:
      - db
      - oss