version: '3.9'
services:
  db:
    container_name: db
    image: postgres:14.1
    restart: unless-stopped
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: development
    network_mode: "host"
  oss:
    container_name: oss
    image: minio/minio:RELEASE.2022-02-07T08-17-33Z
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: development
    command: server --console-address ":9001" /data
    network_mode: "host"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    image: app:${DATETIME}
    environment:
      SSL_ENABLE: true
    restart: unless-stopped
    network_mode: "host"